### ISSUE TITLE
Hard typescript dependency?

### ISSUE THREAD

**Issue by MaffooBristol** [MauricioRobayo/nextjs-google-analytics#278] opened 2022-09-28 15:12 UTC
When I install and run locally, it appears to be fine. Probably because I have some typescript stuff installed globally.

However, when I try and run my (pure javascript, no TS!) app using google app engine, it explodes with a missing dependency of "tslib":
```
Error: Cannot find module 'tslib'
```

I'd prefer to not have to add any typescript peer dependencies when I'm not actually using it. Is there a way of avoiding this with this module? I believe typescript should be an optional extra not a hard requirement.

Cheers
Matt

**Comment by MauricioRobayo** [comment] 2022-10-30 02:23
Hello @MaffooBristol !

Not sure about `tslib` being a hard dependency, it is a [devDependency](https://github.com/MauricioRobayo/nextjs-google-analytics/blob/e81300dbd3b010eb273d396dad8e9e4322a547fa/package.json#L43-L44). If you are running the JS build, it should work fine without the `tslib` module.

Could you share more details about the issue or how to reproduce it? Are you sure it is because of this library?

**Comment by MauricioRobayo** [comment] 2022-10-30 10:45
Ahhh, I believe an old version of the library used to have `tslib` as a dependency, could you try updating to the latest one? There have been some breaking changes so you might want to go through the Readme again, it has been simplified.

**Comment by MauricioRobayo** [comment] 2022-11-21 02:24
Is it ok to close this issue?

**Comment by MauricioRobayo** [comment] 2022-12-04 02:41
Feel free to open a new issue if this persists.

**Closed by MauricioRobayo** 2022-12-04 02:41 UTC
