### ISSUE TITLE
I have this behavior while using this code

### ISSUE THREAD

**Issue by Pnlvfx** [MauricioRobayo/nextjs-google-analytics#204] opened 2022-06-29 21:51 UTC
After more than one month than I use this code in production, I've now noticed that if someone use not to track (tested on Ubuntu 20.0.4 after that I have checked the box 'not to track') the website will fail because every request after the Google analytics request will fail. Anyone know what to do?

**Comment by MauricioRobayo** [comment] 2022-10-30 02:29
Hello @Pnlvfx !

I'm not sure this is caused by the library, and not sure how to reproduce it.

Could you please share more details on how to reproduce this?

**Comment by MauricioRobayo** [comment] 2022-12-04 02:40
Is it Ok to close this PR?

**Closed** 2023-01-24 22:46 UTC
